version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 274201610284.dkr.ecr.us-west-2.amazonaws.com
    - IMAGE_NAME=902477_severityservice
    - IMAGE_URI=274201610284.dkr.ecr.us-west-2.amazonaws.com/902477_severityservice:latest
    - CONTAINER_NAME=902477_severityservice
  build:
    commands:
    - echo Build started on `date`
    - echo $IMAGE_NAME
    - mvn clean package -Ddockerfile.skip -Dmaven.test.skip
    - echo Building the Docker image...
    - docker build -t $IMAGE_NAME .
    
  post_build:
    commands:
    - echo Build completed on `date`
    - echo $(docker images)
    - docker tag $IMAGE_NAME $IMAGE_URI
    - echo Pushing docker image
    - docker push $IMAGE_URI
    - echo Writing image definitions file...
    - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json
artifacts:
  files: imagedefinitions.json